pr:
  branches:
    include:
      - main

pool:
  # vmImage: ubuntu-latest
  vmImage: Default

stages:
  - stage: Build
    jobs:
    - job: Build
      displayName: Run makefile
      steps:
      - task: CmdLine@2
        displayName: Make hello
        inputs:
          script: 'make hello'
          workingDirectory: '$(Build.SourcesDirectory)/CI-CD'